name: SMAP
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - appdirs=1.4.4
  - attrs=22.2.0
  - blosc=1.21.3
  - bokeh=2.4.3
  - boost-cpp=1.78.0
  - bottleneck=1.3.6
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - cachetools=5.3.0
  - cairo=1.16.0
  - cartopy=0.21.1
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=4.2.0
  - cftime=1.6.2
  - charset-normalizer=2.1.1
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - contextlib2=21.6.0
  - contourpy=1.0.7
  - cryptography=39.0.1
  - curl=7.88.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2023.2.0
  - dask-core=2023.2.0
  - distributed=2023.2.0
  - exceptiongroup=1.1.0
  - execnet=1.9.0
  - expat=2.5.0
  - fiona=1.9.1
  - folium=0.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - freexl=1.0.6
  - fsspec=2023.1.0
  - gdal=3.6.2
  - geopandas=0.12.2
  - geopandas-base=0.12.2
  - geos=3.11.1
  - geotiff=1.7.1
  - gettext=0.21.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - heapdict=1.0.1
  - icu=70.1
  - idna=3.4
  - iniconfig=2.0.0
  - intel-openmp=2023.0.0
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - kealib=1.5.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.14
  - lerc=4.0.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcurl=7.88.1
  - libdeflate=1.17
  - libffi=3.4.2
  - libgdal=3.6.2
  - libglib=2.74.1
  - libhwloc=2.8.0
  - libiconv=1.17
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libogg=1.3.4
  - libpng=1.6.39
  - libpq=15.2
  - librttopo=1.1.0
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libvorbis=1.3.7
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - mapclassify=2.5.0
  - markdown-it-py=2.1.0
  - markupsafe=2.1.2
  - matplotlib=3.7.0
  - matplotlib-base=3.7.0
  - mdurl=0.1.0
  - mkl=2022.1.0
  - mock=5.0.1
  - msgpack-python=1.0.4
  - munch=2.5.0
  - munkres=1.1.4
  - netcdf4=1.6.2
  - networkx=3.0
  - numpy=1.24.2
  - odc-geo=0.3.3
  - odc-stac=0.3.5
  - openjpeg=2.5.0
  - openssl=3.0.8
  - packaging=23.0
  - pandas=1.5.3
  - partd=1.3.0
  - path=16.6.0
  - path.py=12.5.0
  - pcre2=10.40
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - planetary-computer=0.4.9
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.6.0
  - poppler=22.12.0
  - poppler-data=0.4.12
  - postgresql=15.2
  - proj=9.1.0
  - psutil=5.9.4
  - pthread-stubs=0.4
  - pycparser=2.21
  - pydantic=1.10.5
  - pygeogrids=0.4.2
  - pygments=2.14.0
  - pykdtree=1.3.6
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyproj=3.4.1
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyshp=2.3.1
  - pysocks=1.7.1
  - pystac=1.6.1
  - pystac-client=0.6.0
  - pytest=7.2.1
  - pytest-shutil=1.7.0
  - python=3.11.0
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pytz=2022.7.1
  - pyyaml=6.0
  - qt-main=5.15.8
  - rasterio=1.3.4
  - requests=2.28.2
  - rich=13.3.1
  - rioxarray=0.13.4
  - rtree=1.0.1
  - scikit-learn=1.2.1
  - scipy=1.10.1
  - setuptools=67.3.2
  - shapely=2.0.1
  - sip=6.7.7
  - six=1.16.0
  - snappy=1.1.9
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - sparse=0.3.1
  - sqlite=3.40.0
  - tbb=2021.7.0
  - tblib=1.7.0
  - termcolor=2.2.0
  - threadpoolctl=3.1.0
  - tiledb=2.13.2
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.65.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - xarray=2023.2.0
  - xerces-c=3.2.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.2.0
  - xz=5.2.6
  - yaml=0.2.5
  - zict=2.2.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - asttokens==2.2.1
      - backcall==0.2.0
      - comm==0.1.2
      - debugpy==1.6.6
      - decorator==5.1.1
      - executing==1.2.0
      - ipykernel==6.21.2
      - ipython==8.10.0
      - jedi==0.18.2
      - jupyter-client==8.0.3
      - jupyter-core==5.2.0
      - matplotlib-inline==0.1.6
      - nest-asyncio==1.5.6
      - parso==0.8.3
      - pickleshare==0.7.5
      - platformdirs==3.0.0
      - prompt-toolkit==3.0.37
      - pure-eval==0.2.2
      - pywin32==305
      - pyzmq==25.0.0
      - stack-data==0.6.2
      - traitlets==5.9.0
      - wcwidth==0.2.6
